spring:
  application:
    name: food-service

  datasource:
    url: jdbc:mysql://localhost:3306/jb2404
    username: root
    password: "{cipher}5ebb2fb10cd84e8b31d93ae60310980308252c8e0446bed4e8b810db7584001f"

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

    driver-class-name: com.mysql.cj.jdbc.Driver;
#Kuch der ke liye bass
#server:
#  port: 9093

#Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
#  Ye actuator lagane ke Badd Add kiye hain
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true


